export const profile = {
  name: "Hein Min Htet",
  title: "Senior Full-Stack Developer",
  about: "Senior Full-Stack Developer with 6+ years of experience designing and shipping production-grade web applications for SaaS platforms, HRMS systems, and real-time dashboards. Deep expertise in React.js, TypeScript, Node.js, NestJS, and PostgreSQL, with hands-on experience in Docker, AWS, and CI/CD pipelines. Proven ability to own features end-to-end — from architecture and API design to deployment and performance optimization. Collaborative remote worker with a track record of mentoring developers and delivering measurable impact at startups and enterprise teams alike.",
  location: "Bangkok, Thailand",
  email: "htetminhein755@gmail.com",
  phone: "+66 962192574",
  github: "https://github.com/Hein21-bot",
};

export const skills = [
  {
    category: "Frontend",
    icon: "🎨",
    items: [
      { name: "React.js",    level: "expert" },
      { name: "Next.js",     level: "expert" },
      { name: "Vue.js",      level: "expert" },
      { name: "TypeScript",  level: "expert" },
      { name: "JavaScript",  level: "expert" },
      { name: "TailwindCSS", level: "expert" },
      { name: "Nuxt.js",     level: "proficient" },
      { name: "Redux",       level: "proficient" },
      { name: "Zustand",     level: "proficient" },
    ],
  },
  {
    category: "Backend",
    icon: "⚙️",
    items: [
      { name: "Node.js",     level: "expert" },
      { name: "NestJS",      level: "expert" },
      { name: "Express.js",  level: "expert" },
      { name: "REST APIs",   level: "expert" },
      { name: "Go (Golang)", level: "proficient" },
      { name: "GraphQL",     level: "proficient" },
      { name: "Prisma",      level: "proficient" },
    ],
  },
  {
    category: "Databases",
    icon: "🗄️",
    items: [
      { name: "PostgreSQL",  level: "expert" },
      { name: "MySQL",       level: "proficient" },
      { name: "DynamoDB",    level: "proficient" },
      { name: "Firebase",    level: "proficient" },
      { name: "SurrealDB",   level: "proficient" },
    ],
  },
  {
    category: "Cloud & DevOps",
    icon: "☁️",
    items: [
      { name: "Git",          level: "expert" },
      { name: "AWS",          level: "proficient" },
      { name: "Docker",       level: "proficient" },
      { name: "Apache",       level: "proficient" },
      { name: "CI/CD",        level: "proficient" },
      { name: "Linux",        level: "proficient" },
      { name: "Kubernetes",   level: "learning" },
    ],
  },
  {
    category: "Other",
    icon: "🔧",
    items: [
      { name: "Socket.io",       level: "expert" },
      { name: "JWT",             level: "proficient" },
      { name: "Google Maps API", level: "proficient" },
      { name: "AI Integration",  level: "proficient" },
      { name: "Agile / Scrum",   level: "proficient" },
    ],
  },
];

export const experience = [
  {
    role: "Freelance Software Developer",
    company: "Independent",
    period: "May 2025 — Present",
    current: true,
    points: [
      "Architected and launched a real-time platform with role-based dashboards supporting 100+ concurrent users.",
      "Built live tracking, notification, and reporting modules that cut manual reporting effort by 40%.",
      "Optimized React/Zustand state management, eliminating 60% of unnecessary re-renders and improving perceived performance.",
    ],
    stack: ["React.js", "Socket.io", "Zustand", "AntD"],
  },
  {
    role: "Software Developer",
    company: "Bardar",
    location: "Sydney",
    period: "May 2024 — Jan 2025",
    points: [
      "Delivered full-stack admin and event management platforms serving multiple product teams across the organization.",
      "Boosted API response times by 30% through query optimization and efficient use of Prisma ORM with PostgreSQL.",
      "Designed and maintained PostgreSQL schemas handling 10,000+ records with real-time read/write operations.",
    ],
    stack: ["React.js", "Node.js", "TypeScript", "PostgreSQL", "Prisma"],
  },
  {
    role: "Freelance Software Developer",
    company: "Independent",
    period: "Oct 2023 — Mar 2024",
    points: [
      "Built a high-throughput barcode generation platform capable of processing 1,000+ labels per batch.",
      "Developed an interactive geospatial visualization tool using real-time map data (Google Maps API).",
      "Delivered multiple full-stack applications using Next.js and Node.js from kickoff to production deployment.",
    ],
    stack: ["Node.js", "Next.js", "JavaScript"],
  },
  {
    role: "Software Developer",
    company: "Trailblazer IT Solutions",
    period: "Jun 2023 — Sep 2023",
    points: [
      "Built a real-time delivery tracking app used daily by 50+ active drivers, integrated with Google Maps API and Firebase.",
      "Reduced status update latency by 70%, significantly improving fleet visibility and operational efficiency.",
    ],
    stack: ["Next.js", "Firebase", "Google Maps API"],
  },
  {
    role: "Software Developer",
    company: "Evercomm Singapore Pte Ltd",
    period: "Nov 2019 — May 2023",
    points: [
      "Led full-stack development of HRMS, survey, and restaurant management systems serving 200+ end users.",
      "Designed and shipped 30+ REST API endpoints with reporting modules enabling real-time analytics for business teams.",
      "Mentored junior developers, established coding standards, and contributed to key architecture decisions across multiple products.",
    ],
    stack: ["Node.js", "React.js", "PostgreSQL", "REST APIs", "SQL"],
  },
];

export const projects = [
  {
    name: "FindEain — Myanmar Rental Platform",
    desc: "Property renters in Myanmar had no centralized platform to find and book homes. Built a full-stack rental marketplace connecting landlords and tenants with property search, booking flows, real-time chat, and localized payment integration.",
    highlights: [
      "Real-time tenant-landlord messaging via Socket.io",
      "Admin approval workflow for property listings",
      "Multi-payment support: KPay, Wave Money, AYA Pay",
      "Role system: Tenant, Landlord, Admin with JWT auth",
    ],
    stack: ["Nuxt.js 3", "Vue 3", "NestJS", "PostgreSQL", "Prisma", "Socket.io", "Redis", "Google Maps API", "Tailwind CSS"],
    icon: "🏠",
    type: "fullstack",
    featured: true,
    link: "https://github.com/Hein21-bot/FindEain",
  },
  {
    name: "Real-time Role Dashboard",
    desc: "Client needed live visibility across a multi-role operation with no data lag. Built a real-time platform with role-based views for users, agents, and admins — featuring live tracking, custom reporting modules, and instant push notifications.",
    highlights: [
      "Live data sync via Socket.io across 3 user roles",
      "Custom reporting engine with real-time charts",
      "Role-based permission system for users, agents, admins",
      "Live notifications and in-app alert system",
    ],
    stack: ["React.js", "Socket.io", "Zustand", "AntD", "Node.js"],
    icon: "📊",
    type: "fullstack",
    featured: true,
  },
  {
    name: "HRMS Platform",
    desc: "Evercomm Singapore needed an in-house system to manage HR, surveys, and restaurant operations. Led end-to-end development over 2.5 years — from architecture through deployment — building a multi-module platform central to daily operations.",
    highlights: [
      "Served 200+ employees across HR, survey, and restaurant modules",
      "Led a team of developers, enforced coding standards",
      "2.5 years in production — full ownership from architecture to deployment",
      "Built custom reporting engine with real-time data visuals",
    ],
    stack: ["Node.js", "React.js", "PostgreSQL", "REST API"],
    icon: "🏢",
    type: "fullstack",
    featured: true,
  },
  {
    name: "Event Management System",
    desc: "Admin dashboard for event tools with real-time UI updates, TypeScript backend, and Prisma database layer.",
    stack: ["React.js", "TypeScript", "Node.js", "PostgreSQL", "Prisma"],
    icon: "🎫",
    type: "fullstack",
  },
  {
    name: "Delivery Tracking App",
    desc: "Real-time delivery tracking web app with map visualizations, Firebase auth, and responsive mobile-first UI.",
    stack: ["Next.js", "Firebase", "Google Maps API"],
    icon: "🚚",
    type: "frontend",
  },
  {
    name: "Barcode Generation Tool",
    desc: "Full-stack barcode generation tool with optimized data flow, from backend logic to clean frontend interface.",
    stack: ["Node.js", "JavaScript", "Next.js"],
    icon: "🔲",
    type: "fullstack",
  },
  {
    name: "Map Visualization Platform",
    desc: "Interactive geographical map platform with advanced frontend visualizations and secure backend data endpoints.",
    stack: ["Next.js", "Node.js", "REST API"],
    icon: "🗺",
    type: "frontend",
  },
  {
    name: "SMT — Myanmar Video Tools",
    desc: "AI-powered video processing suite for Myanmar content creators. Converts YouTube videos into Myanmar narrated recaps, dubs videos with Myanmar text-to-speech, and replaces Chinese subtitles with Myanmar translations.",
    stack: ["Vue.js", "Node.js", "Python", "Gemini API", "FFmpeg", "Docker", "yt-dlp"],
    icon: "🎬",
    type: "fullstack",
    link: "https://github.com/Hein21-bot/recap-project",
  },
  {
    name: "Patient Registration System",
    desc: "Healthcare patient registration platform with real-time updates synced live across multiple browser sessions. Built for the Agnos Health technical assessment.",
    stack: ["Next.js", "TypeScript", "Socket.io", "Tailwind CSS", "Node.js"],
    icon: "🏥",
    type: "fullstack",
    link: "https://patient-registration-op8i.onrender.com/",
  },
  {
    name: "Dota 2 Esport Tracker",
    desc: "Dota 2 tournament tracker syncing live match data from OpenDota and PandaScore APIs on a cron schedule. Golang backend with Neon PostgreSQL, deployed on Cloudflare Pages.",
    stack: ["Golang", "Gin", "GORM", "PostgreSQL", "Neon DB", "OpenDota API", "PandaScore API"],
    icon: "🎮",
    type: "fullstack",
    link: "https://esport-tracker.pages.dev/",
  },
  {
    name: "NovelBin — Myanmar Novel Reader",
    desc: "Full-stack Myanmar-translated Chinese web novel platform with SSR, dark/light mode, admin panel, and a self-pinging Express backend on Hugging Face Spaces backed by AWS DynamoDB.",
    stack: ["Nuxt 3", "Vue 3", "Node.js", "Express", "AWS DynamoDB", "AWS SDK v3", "Docker"],
    icon: "📖",
    type: "fullstack",
    link: "https://novel-fe.pages.dev/",
  },
];

export const learning = [
  { name: "Kubernetes",        icon: "☸️" },
  { name: "System Design",     icon: "📐" },
  { name: "AWS Advanced",      icon: "☁️" },
];
